[package]
name = "detours"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
name = "script_detours"

[dependencies]
formats = { path = "../../formats"}
winapi = {version="0.3", features = ["consoleapi"]}

