[package]
name = "gltf_to_xmac"
version = "0.1.0"
edition = "2021"

[dependencies]
formats = { path = "../../formats" }
serde_json = "1.0"
serde = { workspace = true }
gltf = { workspace = true , features = ["utils"]}
